### ISSUE TITLE
Get-CiresonportalUserSupportgroupMember.ps1 does not work

### ISSUE THREAD

**Issue by Reittier** [lazywinadmin/CiresonPortalPS#5]
Hi,
you have a typo in Line 20 of "\Public\Get-CiresonPortalUserSupportGroupMember.ps1", thats why that function does not work. If you rename the parameter from SupporGroupID to Suppor**t**GroupID it works just fine, because of the query in Line 37.

Since I do not exactly know how to use source control in public git projects... I just decided to make an issue. Hope this helps anyone and not just me :)

**Comment by lazywinadmin** [comment]
Thanks @Reittier ! Fixed in the following commit https://github.com/lazywinadmin/CiresonPortalPS/commit/ae291f639c5bded59583bdb8099548cf80f7ba96
